# **AIM: Implementation of Python Basic Libraries such as Statistics, Math, Numpy and Scipy.**
    a) Usage of methods such as floor ( ), ceil ( ), sqrt ( ), isqrt ( ), gcd ( ) etc.
    b) Usage of attributes of array such as ndim, shape, size, methods such as sum ( ), mean ( ), sort ( ), sin ( ) etc.
    c) Usage of methods such as det ( ), eig ( ) etc.
    d) Consider a list data type (1D) then reshape it into 2D, 3D matrix using numpy.
    e) Generate random matrices using numpy.
    f)  Find the determinant of a matrix using scipy.
    g)  Find eigen value and eigenvector of a matrix using scipy.


In [ ]:
# a) Usage of methods such as floor ( ), ceil ( ), sqrt ( ), isqrt ( ), gcd ( ) etc.

import math

marks = 87.6

section_A = 36
section_B = 48

floor_value = math.floor(marks)
ceil_value = math.ceil(marks)

sq_root = math.sqrt(marks)
int_sq_root = math.isqrt(floor_value)

max_groups = math.gcd(section_A, section_B)


print("Original Marks:", marks)
print("Floor Marks:", floor_value)
print("Ceil Marks:", ceil_value)
print("Square Root of Marks:", sq_root)
print("Integer square root:", int_sq_root)
print("Maximum Equal Groups:", max_groups)


Original Marks: 87.6
Floor Marks: 87
Ceil Marks: 88
Square Root of Marks: 9.359487165438072
Integer square root: 9
Maximum Equal Groups: 12


In [ ]:
# b) Usage of attributes of array such as ndim, shape, size, methods such as sum ( ), mean ( ), sort ( ), sin ( ) etc.

import numpy as np

arr = np.array([[1,2,3],
                [7,10,0],
                 [4,5,6]])

dimension = arr.ndim
shape = arr.shape
size = arr.size
total = np.sum(arr)
avg = np.mean(arr)
sorted_arr = np.sort(arr)  # row wise sorting
sorted_arr1 = np.sort(arr, axis=0)  # column wise sorting
sine_of_elem = np.sin(arr)

print("Dimension of the array arr is:", dimension)
print("Shape of the array arr is:", shape)
print("Size of the array arr is:", size)
print("Sum of the elements of array arr is:", total)
print("Average of the elements array arr is:", avg)
print("Row wise sorted arr is:\n", sorted_arr)
print("Column wise sorted arr is:\n", sorted_arr1)
print("Sine of Each element of arr is:\n", sine_of_elem)

Dimension of the array arr is: 2
Shape of the array arr is: (3, 3)
Size of the array arr is: 9
Sum of the elements of array arr is: 38
Average of the elements array arr is: 4.222222222222222
Row wise sorted arr is:
 [[ 1  2  3]
 [ 0  7 10]
 [ 4  5  6]]
Column wise sorted arr is:
 [[ 1  2  0]
 [ 4  5  3]
 [ 7 10  6]]
Sine of Each element of arr is:
 [[ 0.84147098  0.90929743  0.14112001]
 [ 0.6569866  -0.54402111  0.        ]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [ ]:
# c) Usage of methods such as det ( ), eig ( ) etc.

arr1 = np.array([[1,2],
                [3,4]])

det_value = np.linalg.det(arr1)
eig_val = np.linalg.eig(arr1)

print("Determinant Value of arr1 is:", det_value)
print("Eigen values and Vectors are\n:", eig_val)

Determinant Value of arr1 is: -2.0000000000000004
Eigen values and Vectors are
: EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
# d) Consider a list data type (1D) then reshape it into 2D, 3D matrix using numpy.

arr2 = np.array([1,2,3,4,5,6])

two_D  = arr2.reshape(2,3)
three_D = arr2.reshape(1,2,3)

print("Two Dimensional Form of Array arr2 is:\n", two_D)
print("Three Dimensional Form of Array arr2 is:\n", three_D)

Two Dimensional Form of Array arr2 is:
 [[1 2 3]
 [4 5 6]]
Three Dimensional Form of Array arr2 is:
 [[[1 2 3]
  [4 5 6]]]


In [ ]:
# e) Generate random matrices using numpy.

random_mat = np.random.rand(2,3)
random_mat1 = np.random.rand(5)

print("Random Matrices are:\n", random_mat, "\n And \n", random_mat1)


Random Matrices are:
 [[0.95298023 0.27964282 0.96599442]
 [0.66127671 0.04014721 0.48967147]] 
 And 
 [0.18238202 0.56601706 0.85691374 0.21379904 0.16462493]


In [ ]:
# f)  Find the determinant of a matrix using scipy.
# g)  Find eigen value and eigenvector of a matrix using scipy.

import numpy as np
from scipy import linalg

A = np.array([[1, 2],
              [3, 4]])

det_A = linalg.det(A)
eigen_values, eigen_vectors = linalg.eig(A)

print("Determinant:", det_A)
print("Eigen Values:\n", eigen_values)
print("Eigen Vectors:\n", eigen_vectors)


Determinant: -2.0
Eigen Values:
 [-0.37228132+0.j  5.37228132+0.j]
Eigen Vectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
