# 2 (ii) a) Creation and Loading different types of datasets in Python using the required libraries. 
* i. Creation using pandas    
* ii. Loading CSV dataset files using Pandas 
* iii. Loading datasets using sklearn
#        b) Write a python program to compute Mean, Median, Mode, Variance, Standard Deviation using Datasets.
#        c) Demonstrate various data pre-processing techniques for a given dataset. Write a python program to compute 
* i. Reshaping the data    
* ii. Filtering the data   
* iii. Merging the data     
* iv. Handling the missing values in datasets 
* v. Feature Normalization: Min-max normalization


In [43]:
# 2 (ii) a) i. Creation of Dataset using Pandas

import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name":       ["vikash", "shubham", "amit", "roshan", "aayush"],
    "Math":       [85, 90, 78, 92, 88],
    "Science":    [80, 75, 95, 85, 70],
    "English":    [88, 82, 79, 91, 84],
}

df = pd.DataFrame(data)

print("Created DataFrame using Pandas:\n",df)
print(f"\nShape   : {df.shape}")
print(f"Columns : {list(df.columns)}")  

Created DataFrame using Pandas:
    Student_ID     Name  Math  Science  English
0         101   vikash    85       80       88
1         102  shubham    90       75       82
2         103     amit    78       95       79
3         104   roshan    92       85       91
4         105   aayush    88       70       84

Shape   : (5, 5)
Columns : ['Student_ID', 'Name', 'Math', 'Science', 'English']


In [6]:
# 2 (ii) a) ii. Loading CSV Dataset Using Pandas

import pandas as pd

df = pd.read_csv("airline_ticket_prices_dataset.csv")

print("CSV Dataset Loaded Successfully!")
print(f"\nShape   : {df.shape[0]} rows × {df.shape[1]} columns")
print(f"Columns : {list(df.columns)}")

print("\nFirst 5 Rows:")
print(df.head())

CSV Dataset Loaded Successfully!

Shape   : 250 rows × 8 columns
Columns : ['Ticket_ID', 'Airline', 'Origin', 'Destination', 'Distance_km', 'Class', 'Days_Before_Departure', 'Price_USD']

First 5 Rows:
   Ticket_ID          Airline    Origin Destination  Distance_km     Class  \
0          1           Saudia    Mumbai       Paris         2643   Economy   
1          2           Etihad  Istanbul      Jeddah         8266  Business   
2          3  British Airways     Dubai      Riyadh         2698     First   
3          4         Emirates    London    Istanbul         7956     First   
4          5    Qatar Airways      Doha       Dubai         1308  Business   

   Days_Before_Departure  Price_USD  
0                     28     555.30  
1                     98    2070.27  
2                     21    1883.11  
3                     24    5349.65  
4                     60     516.19  


In [ ]:
# 2 (ii) a) iii. Loading Datasets Using sklearn

import pandas as pd
from sklearn import datasets

iris    = datasets.load_iris()   
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df["Species"] = [iris.target_names[t] for t in iris.target]

print("Iris Dataset")
print(f"Shape   : {iris_df.shape}")
print(f"Classes : {list(iris.target_names)}")
print("First five rows are:\n",iris_df.head())   

Iris Dataset
Shape   : (150, 5)
Classes : [np.str_('setosa'), np.str_('versicolor'), np.str_('virginica')]
First five rows are:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [ ]:
# b) Mean, Median, Mode, Variance, Standard Deviation

import pandas as pd

df = pd.read_csv('airline_ticket_prices_dataset.csv')

print("Dataset:")
print(df.head())

print("\n--- Price_USD ---")
print("Mean     :", df['Price_USD'].mean())
print("Median   :", df['Price_USD'].median())
print("Mode     :", df['Price_USD'].mode()[0])
print("Variance :", df['Price_USD'].var())
print("Std Dev  :", df['Price_USD'].std())   


Dataset:
   Ticket_ID          Airline    Origin Destination  Distance_km     Class  \
0          1           Saudia    Mumbai       Paris         2643   Economy   
1          2           Etihad  Istanbul      Jeddah         8266  Business   
2          3  British Airways     Dubai      Riyadh         2698     First   
3          4         Emirates    London    Istanbul         7956     First   
4          5    Qatar Airways      Doha       Dubai         1308  Business   

   Days_Before_Departure  Price_USD  
0                     28     555.30  
1                     98    2070.27  
2                     21    1883.11  
3                     24    5349.65  
4                     60     516.19  

--- Price_USD ---
Mean     : 2006.05976
Median   : 1531.2350000000001
Mode     : 106.07
Variance : 2805850.1799774524
Std Dev  : 1675.0672165550409


In [37]:
# c-i) Reshaping the Data
 
import pandas as pd
import numpy as np
 
df = pd.read_csv('airline_ticket_prices_dataset.csv')

prices = df['Price_USD'].values[:12]
print('Original 1-D Price array (first 12):') 
print(prices) 
print(f'Shape: {prices.shape}')
 
reshaped = prices.reshape(4, 3)
print(f'\nReshaped to (4x3):\n{reshaped}')

Original 1-D Price array (first 12):
[ 555.3  2070.27 1883.11 5349.65  516.19 6495.84  439.16 2323.31 3032.38
 2282.17 3257.78 1404.2 ]
Shape: (12,)

Reshaped to (4x3):
[[ 555.3  2070.27 1883.11]
 [5349.65  516.19 6495.84]
 [ 439.16 2323.31 3032.38]
 [2282.17 3257.78 1404.2 ]]


In [39]:
# c-ii) Filtering the Data
 
import pandas as pd
 
df = pd.read_csv('airline_ticket_prices_dataset.csv')
 
economy = df[df['Class'] == 'Economy']
print(f'Economy class tickets : {len(economy)} rows')
print(economy[['Airline', 'Origin', 'Destination', 'Price_USD']].head(3))

Economy class tickets : 89 rows
          Airline  Origin Destination  Price_USD
0          Saudia  Mumbai       Paris     555.30
6        Emirates    Doha       Dubai     439.16
13  Qatar Airways    Doha       Cairo    1485.53


In [ ]:
# c-iii) Merging the Data
 
import pandas as pd
 
df = pd.read_csv('airline_ticket_prices_dataset.csv')
 
df2 = pd.DataFrame({
    'Airline': ['Emirates', 'Etihad', 'Saudia', 'British Airways'],
    'Country': ['UAE', 'UAE', 'Saudi Arabia', 'UK']
})
 
inner = pd.merge(df, df2, on='Airline', how='inner')
print("Inner Join:", inner.shape)
print(inner[['Airline', 'Country', 'Price_USD']].head(3)) 

Inner Join: (124, 9)
           Airline       Country  Price_USD
0           Saudia  Saudi Arabia     555.30
1           Etihad           UAE    2070.27
2  British Airways            UK    1883.11


In [28]:
# c-iv) Handling Missing Values
 
import pandas as pd
import numpy as np
 
df = pd.read_csv('airline_ticket_prices_dataset.csv')
 
# Addding missing values
df.loc[0:5, 'Price_USD'] = np.nan
df.loc[6:8, 'Airline']   = np.nan
 
print("Missing Values:")
print(df.isnull().sum())

# Filling with mean
df['Price_USD'] = df['Price_USD'].fillna(df['Price_USD'].mean())
print("Filled with mean - Price_USD NaN left:", df['Price_USD'].isnull().sum())   


Missing Values:
Ticket_ID                0
Airline                  3
Origin                   0
Destination              0
Distance_km              0
Class                    0
Days_Before_Departure    0
Price_USD                6
dtype: int64
Filled with mean - Price_USD NaN left: 0


In [30]:
# c-v) Min-Max Normalization
 
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
 
df = pd.read_csv('airline_ticket_prices_dataset.csv')
 
features = df[['Distance_km', 'Days_Before_Departure', 'Price_USD']]
 
print("Before Normalization:")
print(features.head(3))
 
scaler = MinMaxScaler()
scaled = scaler.fit_transform(features)
 
df_scaled = pd.DataFrame(scaled, columns=features.columns)
 
print("\nAfter Min-Max Normalization:")
print(df_scaled.head(3))   

Before Normalization:
   Distance_km  Days_Before_Departure  Price_USD
0         2643                     28     555.30
1         8266                     98    2070.27
2         2698                     21    1883.11

After Min-Max Normalization:
   Distance_km  Days_Before_Departure  Price_USD
0     0.199447               0.230769   0.051360
1     0.685571               0.829060   0.224567
2     0.204202               0.170940   0.203169
