<a href="https://colab.research.google.com/github/vikashkr96/Numpy_revision/blob/main/Numpy_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#################      Arrays creation methods in numpy ...........

## 1d array

arr = np.array([1,2,3,4])
print(arr)

# # 2d arrays

arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr2)
print(type(arr2))

## array with all elements as zero or zero matrix

arr_zeros = np.zeros(3)
print(arr_zeros)

## array with all elements as zero or zero matrix

arr_ones = np.ones((2,3))
print(arr_ones)

## imp for creating arrays with np.full() function automatically by giving command

full_array = np.full((5,6),7)
print(full_array)

### creating sequence of numbers in numpy with arange() function .....
   ## similar to range() function in python3

arr= np.arange(1,11,2)
print(arr)

### creating identity matrix in numpy with eye() function

ident_matrix = np.eye(4)
print(ident_matrix)



[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]
[1 3 5 7 9]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#########           operations and properties of numpy arrays ...........

## to check shape of given array

arr_2D = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2D)
print("rows,collumns are : " ,arr_2D.shape)

## to check size ie: no of elements  of given array

arr_2D = np.array([[1,2,3],
                   [4,5,6]])
print("Total no of elements is :",arr_2D.size)

## to check no of dimensions of a given array

arr_2D = np.array([[1,2,3],
                   [4,5,6]])
print(f"The given matrix is of {arr_2D.ndim} dimension")

## to check data type of a given array

arr_2D = np.array([[1,2,3],
                   [4,5,6]])
print(f"The data type of the given matrix is  {arr_2D.dtype}")





[[1 2 3]
 [4 5 6]]
rows,collumns are :  (2, 3)
Total no of elements is : 6
The given matrix is of 2 dimension
The data type of the given matrix is  int64
