In [12]:
import numpy as np

### Array reshaping

arr = np.arange(1,13)
print("Original array is:\n",arr)

reshaped = arr.reshape((3,4))
print("reshaped array is: \n" ,reshaped)

flattened = reshaped.flatten()
print("Flattened array is : \n",flattened)

raveled = reshaped.ravel()
print("ravelled array is : \n",raveled)



Original array is:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped array is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array is : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravelled array is : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
### Transpose of matrix :

arr = np.array([[ 1,  2 , 3,  4],
                [ 5,  6 , 7,  8],
                [ 9, 10, 11, 12]])
print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [23]:
### Numpy array operations / indexing / slicing

## index and slicing

arr = np.arange(1,11)
print(arr)
print("Basic slicing:" ,arr[3:8])
print("Slicing by stepping one value :" ,arr[3:8:2])
print("negative indexing:" ,arr[-3])
print("reversing:" ,arr[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
Basic slicing: [4 5 6 7 8]
Slicing by stepping one value : [4 6 8]
negative indexing: 8
reversing: [10  9  8  7  6  5  4  3  2  1]


In [37]:
## index and slicing  on 2-D array

arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr2)

print("The first row,s 2nd element is:",arr2[1,2])
print("The 1st row is: " , arr2[1])
print("The 1st column is: " , arr2[:,1])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
The first row,s 2nd element is: 6
The 1st row is:  [4 5 6]
The 1st column is:  [2 5 8]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [42]:
## sorting of array
arr3 = np.array([ 1,2,3,2,1,3,5,6,7,8,4,8,4])
print(np.sort(arr3))

### sorting of 2D Array
arr =np.array([[3,1],
               [2,1],
               [3,2]])
print(np.sort(arr,axis=0)) # sort by row
print(np.sort(arr,axis=1)) # sort by column

[1 1 2 2 3 3 4 4 5 6 7 8 8]
[[2 1]
 [3 1]
 [3 2]]
[[1 3]
 [1 2]
 [2 3]]
