# **Advance Operation With Business Examples**

In [29]:
import numpy as np
import matplotlib.pyplot as plt


# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])


# Total sales (yearly)...
print("Yearly Sales : ", np.sum(sales_data[:,1:], axis=0)) # to add all rows in a column

# Total sales in each restaurants...
print("Sales in each restorants :", np.sum(sales_data[:,1:],axis = 1))

# Minimum sales in a year ..
min_sales = np.min(sales_data[:,1:],axis= 0)
print(min_sales)
print("Minimum sale in a year is: ", min(min_sales))

# yearly average sales per restaurant

avg_sales = np.mean(sales_data[0:,1:], axis = 1)
print("yearly average sales per restorant is: ", avg_sales)

# yearly average sales per restaurant (2nd method)

avg_sales_ = np.sum(sales_data[:, 1:], axis=1) / sales_data[:, 1:].shape[1]
print(avg_sales_)

# cummulative sales per restaurant
print("\n Cummulative sales per restaurant:")
cumsum = np.cumsum(sales_data[:,1:])
print(cumsum)



Yearly Sales :  [ 810000  945000 1085000 1240000]
Sales in each restorants : [800000 610000 990000 900000 780000]
[120000 140000 160000 190000]
Minimum sale in a year is:  120000
yearly average sales per restorant is:  [200000. 152500. 247500. 225000. 195000.]
[200000. 152500. 247500. 225000. 195000.]

 Cummulative sales per restaurant:
[ 150000  330000  550000  800000  920000 1060000 1220000 1410000 1610000
 1840000 2100000 2400000 2580000 2790000 3030000 3300000 3460000 3645000
 3850000 4080000]


# **Vectorized Operations**

In [44]:
import numpy as np

vector1 = np.array([[1,2,3,4],[5,6,7,8]])
vector2 = np.array([[9,10,11,12],[13,14,15,16]])

vector_sum = (vector1 + vector2)
vector_diff = (vector2 - vector1)
vector_mul = (vector1 * vector2)

print(f" Vector Sum is: {vector_sum},\n Vector Difference is: {vector_diff}\n And Vector Multiplication is: {vector_mul}")

# dot product
vector3 = np.arange(0,8)
temp = vector3.reshape(4,2)
print(" Dot Product is: ", np.dot(vector1,temp))

 Vector Sum is: [[10 12 14 16]
 [18 20 22 24]],
 Vector Difference is: [[8 8 8 8]
 [8 8 8 8]]
 And Vector Multiplication is: [[  9  20  33  48]
 [ 65  84 105 128]]
 Dot Product is:  [[ 40  50]
 [ 88 114]]


In [50]:
# Angle bt two Vectors (formula => cosine of angle = a dot b upon mag of a and b)

angle_in_deg = np.arccos((np.dot(vector1,temp))/((np.linalg.norm(vector1))*(np.linalg.norm(temp))))  # "np.linalg.norm(vector1)"   is basically the magnitude or normalization of vector 1

print(angle_in_deg)


[[1.33183815 1.27043731]
 [1.0231032  0.83041695]]


In [51]:
# broadcasting in numpy =>   means , suppos we have a scaler eg: 12 and a 3*3 vector matrix
# and we want to divide the vector by the scaler , then we will divid evector once by that scaler but it
# will automatically divided by each element of the vector mnatrix this is called the broadcasting

# for tech intrvws => Broadcasting in NumPy allows arithmetic operations between arrays of different shapes by automatically expanding the smaller
# array to match the shape of the larger one without copying data.

# example:

matrix = np.array([
    [12, 24, 36],
    [48, 60, 72],
    [84, 96, 108]
])

result = matrix / 12
print(result)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
