# Filter

In [4]:
import numpy as np

arr = np.array([2,6,4,8,9,7,4,5,3,8,1])

even_nums = arr[arr%2 == 0]

even_nums     # prints only the even numbers present in the arr

array([2, 6, 4, 8, 4, 8])

# Filter With mask

In [9]:
mask = arr > 5     # actually this portion/ expression is called the mask

print("Numbers greater than 5: ", arr[mask])

# to mask or filter the indices => np.where()

Np_where = np.where(arr > 5)
print("arary of indices where elements in arr is grater than 5: ",Np_where)

Numbers greater than 5:  [6 8 9 7 8]
arary of indices where elements in arr is grater than 5:  (array([1, 3, 4, 5, 9]),)


# Adding and removing data -- Combination


In [15]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3 = np.array([1000011])

combined_arr = np.concatenate((arr1, arr2 , arr3)) # always pass arrays in a tuple
print(combined_arr)
print(arr1.size == arr3.size)   # false

[      1       2       3       4       5       6       7       8       9
      10 1000011]
False


# Adding new **Row and Columns**

In [19]:
original = np.array([[1,2],[3,4]])

new_row = np.array([5,6])
with_new_row = np.vstack((original,new_row))  # alway pass in tuple
print(with_new_row)

new_col = np.array([[1],[0]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 1]
 [3 4 0]]


# deletion

In [21]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,0)  # (array, index to be deleten in sequence)

print("array after deleted :" , deleted)

array after deleted : [2 3 4 5]
