In [5]:
import numpy as np

###  Vector , Matrix , Tensor
vector = np.array([1,2,3,4])
print(vector)

matrix = np.array([[1,2,3],[5,6,7]])
print(matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)



[1 2 3 4]
[[1 2 3]
 [5 6 7]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
##### operations on array

arr = np.arange(12) # sequence of elements
print(arr)

arr= np.reshape(arr ,(3,4)) #rearrange the shape AND then the diamension of the array
print(arr)
arr = reshaped.ravel

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


NameError: name 'reshaped' is not defined